Refactor GitHub Actions workflow to include Rust program execution and cleanup steps

diff --git a/.github/workflows/run.yaml b/.github/workflows/run.yaml
--- a/.github/workflows/run.yaml
+++ b/.github/workflows/run.yaml
@@ -65,16 +65,16 @@ jobs:
         cd ..
         cd ..
         cd ..
-    # Run the Rust program
+    # Test the Rust program
     - name: Run Rust program
-      run: ./hello-world
-      working-directory: ./target/release/temp_files
-      continue-on-error: true
-    # Check exit code
-    - name: Check exit code
       run: |
-        echo "Exit code: $?"
-      if: ${{ failure() }}
+        ./hello-world
+        exit_code=$?
+        if [ $exit_code -ne 0 ]; then
+          echo "Rust program failed with exit code $exit_code"
+          exit 1
+        fi
+      working-directory: ./target/release/temp_files
     # delete the temp_files directory
     - name: Delete temp_files
       run: |
@@ -109,16 +109,16 @@ jobs:
         Compress-Archive -Path "hello_windows" hello-windows.zip
         cd ..
         cd ..
-    # Run the Rust program
+    # Test the Rust program
     - name: Run Rust program
-      run: ./hello-world.exe
-      working-directory: ./target/release/hello_windows
-      continue-on-error: true
-    # Check exit code
-    - name: Check exit code
       run: |
-        echo "Exit code: $?"
-      if: ${{ failure() }}
+        ./hello-world.exe
+        exit_code=$?
+        if [ $exit_code -ne 0 ]; then
+          echo "Rust program failed with exit code $exit_code"
+          exit 1
+        fi
+      working-directory: ./target/release/hello_windows
     # delete the hello_windows directory
     - name: Delete hello_windows
       run: |
@@ -158,16 +158,16 @@ jobs:
           cd ..
           cd ..
           cd ..
-      # Run the Rust program
+      # Test the Rust program
       - name: Run Rust program
-        run: ./hello-world
-        working-directory: ./target/release/temp_files
-        continue-on-error: true
-      # Check exit code
-      - name: Check exit code
         run: |
-          echo "Exit code: $?"
-        if: ${{ failure() }}
+          ./hello-world
+          exit_code=$?
+          if [ $exit_code -ne 0 ]; then
+            echo "Rust program failed with exit code $exit_code"
+            exit 1
+          fi
+        working-directory: ./target/release/temp_files
       # delete the temp_files directory
       - name: Delete temp_files
         run: |
