run

diff --git a/.github/workflows/test-ffmpeg-env.yaml b/.github/workflows/test-ffmpeg-env.yaml
--- a/.github/workflows/test-ffmpeg-env.yaml
+++ b/.github/workflows/test-ffmpeg-env.yaml
@@ -13,62 +13,62 @@ on:
 # name: Build and Release
 
 jobs:
-  build_on_ubunutu:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-      # Set up ffmpeg environment
-      - name: Install dependencies
-        run: |
-          sudo apt install -y --no-install-recommends clang curl pkg-config
-          sudo apt install libavcodec-dev libavutil-dev libavformat-dev libavfilter-dev libavdevice-dev
-      - name: Install rust toolchain
-        uses: dtolnay/rust-toolchain@v1
-        with:
-          toolchain: stable
-      - name: Set up Rust
-        uses: actions-rs/toolchain@v1
-        with:
-          toolchain: stable
-      # Build the project
-      - name: Build Project
-        run: cargo build --release
-        # run: cargo build --verbose --release
-      # List the files in the target/release directory
-      - name: List Files
-        run: ls -R ./target/release
-      # copy and compress the binary and library into a zip file
-      - name: Copy and Compress Binary
-        run: |
-          cd ./target/release
-          mkdir -p temp_files/libs
-          cp hello-world temp_files/
-          cp *.so temp_files/libs/
-          cd temp_files
-          cd ..
-          cd ..
-          cd ..
-      # Test the Rust program
-      - name: Run Rust program
-        run: |
-          ./hello-world
-          exit_code=$?
-          if [ $exit_code -ne 0 ]; then
-            echo "Rust program failed with exit code $exit_code"
-            exit 1
-          fi
-          zip -r ../hello-ubuntu.zip .
-        working-directory: ./target/release/temp_files
-      # delete the temp_files directory
-      - name: Delete temp_files
-        run: |
-          rm -rf ./target/release/temp_files
-      # then upload the zip to the release
-      - name: Archive code coverage results
-        uses: actions/upload-artifact@v4
-        with:
-          name: hello_ubuntu-output-report
-          path: ./target/release/hello-ubuntu.zip
+  # build_on_ubunutu:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     # Set up ffmpeg environment
+  #     - name: Install dependencies
+  #       run: |
+  #         sudo apt install -y --no-install-recommends clang curl pkg-config
+  #         sudo apt install libavcodec-dev libavutil-dev libavformat-dev libavfilter-dev libavdevice-dev
+  #     - name: Install rust toolchain
+  #       uses: dtolnay/rust-toolchain@v1
+  #       with:
+  #         toolchain: stable
+  #     - name: Set up Rust
+  #       uses: actions-rs/toolchain@v1
+  #       with:
+  #         toolchain: stable
+  #     # Build the project
+  #     - name: Build Project
+  #       run: cargo build --release
+  #       # run: cargo build --verbose --release
+  #     # List the files in the target/release directory
+  #     - name: List Files
+  #       run: ls -R ./target/release
+  #     # copy and compress the binary and library into a zip file
+  #     - name: Copy and Compress Binary
+  #       run: |
+  #         cd ./target/release
+  #         mkdir -p temp_files/libs
+  #         cp hello-world temp_files/
+  #         cp *.so temp_files/libs/
+  #         cd temp_files
+  #         cd ..
+  #         cd ..
+  #         cd ..
+  #     # Test the Rust program
+  #     - name: Run Rust program
+  #       run: |
+  #         ./hello-world
+  #         exit_code=$?
+  #         if [ $exit_code -ne 0 ]; then
+  #           echo "Rust program failed with exit code $exit_code"
+  #           exit 1
+  #         fi
+  #         zip -r ../hello-ubuntu.zip .
+  #       working-directory: ./target/release/temp_files
+  #     # delete the temp_files directory
+  #     - name: Delete temp_files
+  #       run: |
+  #         rm -rf ./target/release/temp_files
+  #     # then upload the zip to the release
+  #     - name: Archive code coverage results
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: hello_ubuntu-output-report
+  #         path: ./target/release/hello-ubuntu.zip
 
   build_on_windows:
     runs-on: windows-latest
@@ -79,13 +79,13 @@ jobs:
       # Set up ffmpeg environment
       - name: Install dependencies
         run: |
-          vcpkg install clang:x64-windows
-          vcpkg install pkg-config:x64-windows
-          vcpkg install libavcodec:x64-windows
-          vcpkg install libavutil:x64-windows
-          vcpkg install libavformat:x64-windows
-          vcpkg install libavfilter:x64-windows
-          vcpkg install libavdevice:x64-windows
+          choco install clang
+          choco install pkg-config
+          choco install libavcodec
+          choco install libavutil
+          choco install libavformat
+          choco install libavfilter
+          choco install libavdevice
 
         #  curl:x64-windows 
         
